# Generated by Django 4.2 on 2024-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
